name: CI Pipeline
on:
  pull_request:
    branches:
      - develop
      - main

  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '7.4'

      - name: Install dependencies
        run: composer install --no-interaction --prefer-dist --no-progress

      - name: Setup ci-phpunit-test
        run: php vendor/kenjis/ci-phpunit-test/install.php

      - name: Run tests
        run: |
          cd application/tests
          phpunit --verbose